import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Form from '@/components/Form/index'
import Buttons from '@/components/Buttons'
import Image from 'next/image'
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.phoneForm}>
          <div className={styles.instaPhone}>
            <Image src={'/Image/instagramphone.png'} alt={'insta-logo'} width={450} height={660}/>
          </div>
          <div className={styles.formSignUp}>
            <div className={styles.loginContainer}>
              <div className={styles.instagramLogo}>
                <Image src={'/Image/instagramlogo.png'} alt={'insta-logo'} width={190} height={64}/>
              </div>
              <Form/>
              <Buttons/>
              <br/>
              <div className={styles.orLine}>
                OR
              </div>
              <div className={styles.facebookParagraph}>
                  <p>Log in with Facebook</p>
              </div>
              <div className={styles.tinyParagraph}>
                <p>Forgot password?</p>
              </div>
            </div>
            <div className={styles.containerTwo}>
              <p>Don't have an account? <span className={styles.signUp}>Sign up</span></p>
            </div>
            <p className={styles.paragraph}>Get the app.</p>
             <div className={styles.appLogo}>
              <Image src={'/Image/appstorelogo.png'} alt={'store-logo'} width={290} height={41.5}/>
            </div>
          </div> 
        </div>
        <Footer/>
      </main>
    </>
  )
}
